ExperimentMetaData:
  name: "Simple Prediction Model"
  experiment_dir: null # if null then defined from name, type and identifier
  experiment_name: SummaryPrediction
  experiment_type: Basic
  experiment_indentifier: null
  results_dir: ./drive/MyDrive/Crypto/Experiments/

PredictionModel:
  class_name: SummaryPredictionModel
  PastEncoder:
    class_name: LSTMModel
    input_dim: 4
    hidden_dim: 10
    layer_num: 1
    output_dim: 25 

  PredictionHead:
    class_name: MLPRegressionHead
    input_dim: 25 # same as encoder output
    hidden_dims: [20]
    output_dim: 29

TrainingParameters:
  learning_rate: 0.001
  num_epochs: 3
  debug: true
  device: "cuda:0"
  
  clip_grad: true
  clip_max_norm: 1.

  save_model_epochs: 10
  save_model_metrics_stopping: false
  save_model_metrics_warming: false
  warm_up_best_model_epoch: 10
  save_model_test_stopping: true

  metric_to_save:
    - null

DataLoaderParameters:
  data_dir: ./drive/MyDrive/Crypto/Data/2024-03-19/
  batch_size: 64
  shuffle: True
  num_workers: 4
  training_split: 0.8